spring:
  application:
    name: ms-pagamento
  datasource:
    url: jdbc:postgresql://${DATABASE_SERVER:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:pagamento_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
server:
  port: 8080
logging:
  file:
    name: log/appfile.log
management:
  endpoints:
    web:
      exposure:
        include: ["routes"]